#
# Jekyll configuration
#
#server: true
destination: ./_site
auto:        false
#server_port: 4000
permalink:   pretty
#paginate:    20
lsi:         false
#lsi:         false
pygments:    true
markdown:    maruku
#markdown:    rdiscount

#
# Site configuration
#
url:          http://spaminvoluntario.com
title:        "Spam involuntario"
description:  Aqu&iacute; mejor nos disculpamos de antemano
author:       Dario Vasconcelos # atom.xml: Name of website's author
email:        dario.vasconcelos@gmail.com # atom.xml: Author email
analytics_id: UA-105994-9 # Google Analytics ID: UA-xxx-xxx
media_version: 4
